name: Overwatch Auto-Tracker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Tracker
        env:
          BATTLE_TAG: ${{ secrets.BATTLE_TAG }}
        run: python main.py
      - name: Commit Files
        run: |
          git config --global user.name "Tracker Bot"
          git config --global user.email "bot@github.com"
          git add history.json badge.json rank_history.png
          git commit -m "Update Stats: $(date)" || echo "No changes"
          git push